### ISSUE TITLE
Si no habéis terminado aún la práctica... NO podéis tener ya releases

### ISSUE THREAD

**Issue by vrivas** [UJA-DAGIL-22-23/d-agil-2022-2023-practica-4-alvaros_alba_francisco#1]
:)

Scrum => entrego mi incremento el último día del proyecto (o en su defecto, cuando no hay más HU que implementar, y está ya toda la documentación terminada).

Scrum => 1 incremento por sprint

Práctica 4 INCLUYE un solo sprint

Si (no ha terminado el Sprint O no he terminado la práctica ) ENTONCES no puedo tener aún incrementos (= releases)

Peeero: sí puedo tener PRE-RELEASES.

Plis, por fi, "silvuplé": cambiad las releases que tenéis para que sean pre-releases. En caso de que no se pueda...¡¡destruidlas!!
Sanks!

**Comment by agl00108** [comment]
hecho
